version: "2"
run:
  build-tags:
    - e2e
linters:
  default: all
  disable:
    - errcheck
    - wrapcheck
    - exhaustruct
    - depguard
    - ireturn
    - wsl
    - godox
    - varnamelen
    - noinlineerr
    - godoclint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: "test/e2e"
        linters:
          - testpackage
          - paralleltest
          - err113
          - mnd
          - gochecknoglobals
          - forbidigo

formatters:
  exclusions:
    generated: lax
