version: "2"
run:
  build-tags:
    - e2e
linters:
  default: all
  disable:
    - errcheck
    - wrapcheck
    - exhaustruct
    - depguard
    - ireturn
    - wsl
    - godox
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

formatters:
  exclusions:
    generated: lax
