/*
Copyright 2025 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	wasmv1alpha1 "github.com/cardil/knative-serving-wasm/pkg/apis/wasm/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// WasmModuleLister helps list WasmModules.
// All objects returned here must be treated as read-only.
type WasmModuleLister interface {
	// List lists all WasmModules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*wasmv1alpha1.WasmModule, err error)
	// WasmModules returns an object that can list and get WasmModules.
	WasmModules(namespace string) WasmModuleNamespaceLister
	WasmModuleListerExpansion
}

// wasmModuleLister implements the WasmModuleLister interface.
type wasmModuleLister struct {
	listers.ResourceIndexer[*wasmv1alpha1.WasmModule]
}

// NewWasmModuleLister returns a new WasmModuleLister.
func NewWasmModuleLister(indexer cache.Indexer) WasmModuleLister {
	return &wasmModuleLister{listers.New[*wasmv1alpha1.WasmModule](indexer, wasmv1alpha1.Resource("wasmmodule"))}
}

// WasmModules returns an object that can list and get WasmModules.
func (s *wasmModuleLister) WasmModules(namespace string) WasmModuleNamespaceLister {
	return wasmModuleNamespaceLister{listers.NewNamespaced[*wasmv1alpha1.WasmModule](s.ResourceIndexer, namespace)}
}

// WasmModuleNamespaceLister helps list and get WasmModules.
// All objects returned here must be treated as read-only.
type WasmModuleNamespaceLister interface {
	// List lists all WasmModules in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*wasmv1alpha1.WasmModule, err error)
	// Get retrieves the WasmModule from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*wasmv1alpha1.WasmModule, error)
	WasmModuleNamespaceListerExpansion
}

// wasmModuleNamespaceLister implements the WasmModuleNamespaceLister
// interface.
type wasmModuleNamespaceLister struct {
	listers.ResourceIndexer[*wasmv1alpha1.WasmModule]
}
