/*
Copyright 2026 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiswasmv1alpha1 "github.com/cardil/knative-serving-wasm/pkg/apis/wasm/v1alpha1"
	versioned "github.com/cardil/knative-serving-wasm/pkg/client/clientset/versioned"
	internalinterfaces "github.com/cardil/knative-serving-wasm/pkg/client/informers/externalversions/internalinterfaces"
	wasmv1alpha1 "github.com/cardil/knative-serving-wasm/pkg/client/listers/wasm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// WasmModuleInformer provides access to a shared informer and lister for
// WasmModules.
type WasmModuleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() wasmv1alpha1.WasmModuleLister
}

type wasmModuleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewWasmModuleInformer constructs a new informer for WasmModule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWasmModuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredWasmModuleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredWasmModuleInformer constructs a new informer for WasmModule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredWasmModuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WasmV1alpha1().WasmModules(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WasmV1alpha1().WasmModules(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WasmV1alpha1().WasmModules(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WasmV1alpha1().WasmModules(namespace).Watch(ctx, options)
			},
		}, client),
		&apiswasmv1alpha1.WasmModule{},
		resyncPeriod,
		indexers,
	)
}

func (f *wasmModuleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredWasmModuleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *wasmModuleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiswasmv1alpha1.WasmModule{}, f.defaultInformer)
}

func (f *wasmModuleInformer) Lister() wasmv1alpha1.WasmModuleLister {
	return wasmv1alpha1.NewWasmModuleLister(f.Informer().GetIndexer())
}
